events {}

http {
  server {
    listen 80;

    location /react/ {
      proxy_pass http://react-frontend:3000/;
    }
    location /api/node/ {
      proxy_pass http://node-backend:4001/;
    }

    location /vue/ {
      proxy_pass http://vue-frontend:3002/;
    }
    location /api/python/ {
      proxy_pass http://python-backend:4002/;
    }

    location /vanilla/ {
      proxy_pass http://vanilla-frontend:3003/;
    }
    location /api/java/ {
      proxy_pass http://java-backend:4003/;
    }

    location / {
      return 302 /react/;   # default landing version
    }
  }
}